import api from './api';

const adminApi = {
  getDashboard: () => api.get('/admin/dashboard'),
  getAnalytics: () => api.get('/admin/analytics'),
  getProducts: (params) => api.get('/admin/products', { params }),
  getProduct: (id) => api.get(`/admin/products/${id}`),
  createProduct: (data) => api.post('/admin/products', data),
  updateProduct: (id, data) => api.put(`/admin/products/${id}`, data),
  deleteProduct: (id) => api.delete(`/admin/products/${id}`),
  getUsers: () => api.get('/admin/users'),
  updateUser: (id, data) => api.put(`/admin/users/${id}`, data),
  deleteUser: (id) => api.delete(`/admin/users/${id}`),
  getOrders: (params) => api.get('/admin/orders', { params }),
  getOrder: (id) => api.get(`/admin/orders/${id}`),
  updateOrderStatus: (id, status) => api.put(`/admin/orders/${id}/status`, { status }),
  getReviews: (params) => api.get('/admin/reviews', { params }),
  deleteReview: (id) => api.delete(`/admin/reviews/${id}`),
  getFeedback: () => api.get('/admin/feedback'),
  getCategories: () => api.get('/admin/categories'),
  createCategory: (data) => api.post('/admin/categories', data),
  updateCategory: (id, data) => api.put(`/admin/categories/${id}`, data),
  deleteCategory: (id) => api.delete(`/admin/categories/${id}`),
  getInventory: () => api.get('/admin/inventory'),
  updateInventory: (id, data) => api.put(`/admin/inventory/${id}`, data),
  getInventoryHistory: (id) => api.get(`/admin/inventory/${id}/history`),
  getWarehouses: () => api.get('/admin/warehouses'),
  createWarehouse: (data) => api.post('/admin/warehouses', data),
  updateWarehouse: (id, data) => api.put(`/admin/warehouses/${id}`, data),
  deleteWarehouse: (id) => api.delete(`/admin/warehouses/${id}`),
  getPayments: () => api.get('/admin/payments'),
  getSettings: () => api.get('/admin/settings'),
  updateSettings: (data) => api.put('/admin/settings', data),
  getNotifications: () => api.get('/admin/notifications'),
  sendNotification: (data) => api.post('/admin/notifications', data),
  markNotificationRead: (id) => api.patch(`/admin/notifications/${id}/read`),
  markNotificationsRead: () => api.patch('/admin/notifications/read-all'),
  deleteNotification: (id) => api.delete(`/admin/notifications/${id}`),
};

export default adminApi;
