import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertCircle, Bell, CheckCircle, CreditCard, MoreVertical, Package, ShoppingBag, Trash2, Truck, UserPlus } from 'lucide-react';
import { useNotifications } from '../../context/NotificationContext';

const iconFor = (type = '') => type.includes('PAYMENT') ? CreditCard : type === 'USER_REGISTERED' ? UserPlus : type.includes('SHIPPED') ? Truck : type.includes('DELIVERED') ? CheckCircle : type.includes('FAILED') ? AlertCircle : type.includes('ORDER') ? ShoppingBag : Package;
const ago = (date) => { const seconds = Math.max(1, Math.floor((Date.now() - new Date(date)) / 1000)); return seconds < 60 ? 'just now' : seconds < 3600 ? `${Math.floor(seconds / 60)}m ago` : seconds < 86400 ? `${Math.floor(seconds / 3600)}h ago` : `${Math.floor(seconds / 86400)}d ago`; };

export default function NotificationPopover({ admin = false, onClose }) {
  const { notifications, unreadCount, markRead, markAllRead, deleteNotification } = useNotifications(); const [menu, setMenu] = useState(null); const ref = useRef(null);
  useEffect(() => { const close = (e) => { if (!ref.current?.contains(e.target)) { setMenu(null); onClose?.(); } }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close); }, [onClose]);
  const visible = notifications.slice(0, 6); const destination = admin ? '/admin/notifications' : '/notifications';
  return <section ref={ref} className="absolute right-0 top-12 z-50 w-[min(23rem,calc(100vw-1.5rem))] overflow-visible rounded-xl border border-slate-200 bg-white shadow-xl"><header className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><b className="text-slate-900">Notifications</b><button disabled={!unreadCount} onClick={markAllRead} className="text-xs font-semibold text-primary-600 disabled:text-slate-400">Mark all read</button></header><div className="max-h-96 overflow-y-auto">{visible.length ? visible.map((item) => { const Icon = iconFor(item.type); return <article onClick={() => !item.read && markRead(item._id)} className={`relative flex cursor-pointer gap-3 border-b border-slate-100 px-4 py-3 transition hover:bg-slate-50 ${item.read ? '' : 'bg-amber-50/60'}`} key={item._id}><span className={`mt-0.5 rounded-lg p-2 ${item.read ? 'bg-slate-100 text-slate-500' : 'bg-amber-100 text-amber-700'}`}><Icon size={16} /></span><div className="min-w-0 flex-1 pr-5"><p className={`truncate text-sm ${item.read ? 'font-medium' : 'font-bold'}`}>{item.title}</p><p className="truncate text-xs text-slate-500">{item.message}</p><time className="mt-1 block text-[11px] text-slate-400">{ago(item.createdAt)}</time></div>{!item.read && <i className="mt-2 h-2 w-2 rounded-full bg-amber-500" />}<div className="absolute right-1 top-1"><button onClick={(e) => { e.stopPropagation(); setMenu(menu === item._id ? null : item._id); }} className="rounded p-1 text-slate-400 hover:bg-slate-200"><MoreVertical size={16} /></button>{menu === item._id && <div className="absolute right-0 top-7 w-40 rounded-lg border bg-white p-1 shadow-lg"><>{!item.read && <button onClick={(e) => { e.stopPropagation(); markRead(item._id); setMenu(null); }} className="w-full rounded px-2 py-2 text-left text-xs hover:bg-slate-50">Mark as read</button>}<button onClick={(e) => { e.stopPropagation(); deleteNotification(item._id); setMenu(null); }} className="flex w-full items-center gap-1 rounded px-2 py-2 text-left text-xs text-red-600 hover:bg-red-50"><Trash2 size={13} /> Delete</button></></div>}</div></article>; }) : <p className="p-8 text-center text-sm text-slate-500">No notifications.</p>}</div><Link onClick={onClose} to={destination} className="block p-3 text-center text-sm font-semibold text-primary-600 hover:bg-slate-50">View all notifications</Link></section>;
}
