import { useEffect, useState } from 'react';
import adminApi from '../../services/adminApi';
import toast from 'react-hot-toast';

export default function AdminCategories() {
  const [categories, setCategories] = useState([]); const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [search, setSearch] = useState('');
  const load = () => adminApi.getCategories().then(({ data }) => setCategories(data.categories)).catch(() => toast.error('Unable to load categories'));
  useEffect(() => { load(); }, []);
  const add = async (e) => { e.preventDefault(); try { await adminApi.createCategory({ name, description }); setName(''); setDescription(''); toast.success('Category added'); load(); } catch (e) { toast.error(e.response?.data?.error || 'Unable to add category'); } };
  const remove = async (c) => { if (!window.confirm(`Delete ${c.name}? Products will not be deleted.`)) return; try { await adminApi.deleteCategory(c._id); toast.success('Category deleted'); load(); } catch (e) { toast.error(e.response?.data?.error || 'Unable to delete category'); } };
  const shown = categories.filter((c) => c.name.toLowerCase().includes(search.toLowerCase()));
  return <div className="space-y-6"><div><p className="text-sm text-[var(--color-text-secondary)]">Catalog taxonomy</p><h2 className="text-3xl font-display">Categories</h2></div><form onSubmit={add} className="grid gap-3 rounded-[14px] border border-[var(--color-border)] bg-surface p-5 md:grid-cols-[1fr_2fr_auto]"><input required className="admin-input mt-0" value={name} onChange={(e) => setName(e.target.value)} placeholder="Category name" /><input className="admin-input mt-0" value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Description (optional)" /><button className="btn-primary">Add category</button></form><input className="admin-input max-w-md" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search categories" /><div className="overflow-x-auto rounded-[14px] border border-[var(--color-border)] bg-surface"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-ivory text-[var(--color-text-secondary)]"><tr><th className="p-4">Name</th><th className="p-4">Description</th><th className="p-4">Products</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody>{shown.length ? shown.map((c) => <tr className="border-t" key={c._id}><td className="p-4 font-semibold">{c.name}</td><td className="p-4 text-[var(--color-text-secondary)]">{c.description || '—'}</td><td className="p-4">{c.productCount}</td><td className="p-4"><span className="status-badge bg-emerald-50 text-emerald-700">{c.active ? 'Active' : 'Inactive'}</span></td><td className="p-4">{c.legacy ? <span className="text-xs text-slate-400">Legacy category</span> : <button onClick={() => remove(c)} className="text-red-600">Delete</button>}</td></tr>) : <tr><td className="p-8 text-center text-[var(--color-text-secondary)]" colSpan="5">No categories found.</td></tr>}</tbody></table></div></div>;
}