import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import adminApi from '../../services/adminApi';
import toast from 'react-hot-toast';

const statuses = ['pending', 'processing', 'shipped', 'delivered', 'cancelled'];
export default function AdminOrderDetails() {
  const { id } = useParams(); const [order, setOrder] = useState(null);
  useEffect(() => { adminApi.getOrder(id).then(({ data }) => setOrder(data.order)).catch(() => toast.error('Failed to load order')); }, [id]);
  if (!order) return <p className="skeleton mx-auto h-40 w-full max-w-3xl" />;
  const delivery = order.shippingAddress || {};
  const update = async (status) => { try { const { data } = await adminApi.updateOrderStatus(id, status); setOrder(data.order); toast.success(data.emailSent ? 'Order updated and email sent' : 'Order updated; email was not sent'); } catch (error) { toast.error(error.response?.data?.error || 'Failed to update order'); } };
  return <div className="max-w-4xl space-y-6"><Link to="/admin/orders" className="text-sm font-medium text-accent">&larr; Back to orders</Link><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm text-[var(--color-text-secondary)]">Order {order._id}</p><h2 className="text-3xl font-display">Order details</h2></div><select value={order.status} onChange={(e) => update(e.target.value)} className="rounded-lg border px-3 py-2 capitalize">{statuses.map((status) => <option key={status}>{status}</option>)}</select></div><div className="grid gap-6 md:grid-cols-2"><section className="rounded-[14px] border border-[var(--color-border)] bg-surface p-6"><h3 className="font-bold">Customer information</h3><p className="mt-4 text-sm">{delivery.fullName || order.user?.name}</p><a className="block text-sm text-accent" href={`mailto:${delivery.email || order.user?.email}`}>{delivery.email || order.user?.email}</a><a className="block text-sm text-accent" href={`tel:${delivery.phone || order.user?.phone}`}>{delivery.phone || order.user?.phone || 'No phone provided'}</a></section><section className="rounded-[14px] border border-[var(--color-border)] bg-surface p-6"><h3 className="font-bold">Delivery information</h3><p className="mt-4 text-sm">{delivery.address || delivery.street}</p><p className="text-sm text-[var(--color-text-secondary)]">{delivery.area}, {delivery.city}, {delivery.province || delivery.state}</p><p className="text-sm text-[var(--color-text-secondary)]">Ward {delivery.ward} {delivery.postalCode || delivery.zipCode}</p><p className="text-sm text-[var(--color-text-secondary)]">{delivery.country}</p>{delivery.deliveryInstructions && <p className="mt-3 text-sm"><b>Instructions:</b> {delivery.deliveryInstructions}</p>}</section></div><section className="rounded-[14px] border border-[var(--color-border)] bg-surface p-6"><h3 className="font-bold">Products</h3>{order.items.map((item) => <div className="flex justify-between border-b border-[var(--color-border)] py-4 text-sm" key={`${item.product?._id || item.product}-${item.name}`}><span>{item.name} x {item.quantity}</span><b>${(item.price * item.quantity).toFixed(2)}</b></div>)}<div className="mt-5 flex justify-between text-lg font-bold"><span>Total</span><span>${Number(order.totalAmount).toFixed(2)}</span></div><p className="mt-3 text-sm text-[var(--color-text-secondary)]">Payment: <span className="capitalize">{order.paymentMethod}</span> / <span className="capitalize">{order.paymentStatus}</span>{order.paymentId ? ` / ${order.paymentId}` : ''}</p></section></div>;
}
