import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Pencil, Trash2 } from 'lucide-react';
import adminApi from '../../services/adminApi';
import toast from 'react-hot-toast';

export default function AdminProducts() {
  const [products, setProducts] = useState([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); adminApi.getProducts({ search }).then(({ data }) => setProducts(data.products)).catch(() => toast.error('Failed to load products')).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, [search]);
  const remove = async (id) => { if (!window.confirm('Are you sure you want to delete this product?')) return; try { await adminApi.deleteProduct(id); toast.success('Product deleted'); load(); } catch { toast.error('Failed to delete product'); } };
  return <div className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm text-[var(--color-text-secondary)]">Catalog control</p><h2 className="text-3xl font-display">Products</h2></div><Link to="/admin/products/new" className="btn-primary inline-flex items-center justify-center gap-2"><Plus size={18} />Add product</Link></div><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search products" className="w-full max-w-md rounded-lg border border-[var(--color-border)] bg-surface px-4 py-3" /><div className="overflow-x-auto rounded-[14px] border border-[var(--color-border)] bg-surface shadow-sm"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-ivory text-[var(--color-text-secondary)]"><tr>{['Product','Category','Price','Stock','Rating','Featured','Actions'].map((h) => <th className="p-4" key={h}>{h}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan="7" className="p-8 text-center">Loading products...</td></tr> : products.length ? products.map((p) => <tr className="border-t border-[var(--color-border)]" key={p._id}><td className="flex items-center gap-3 p-4"><img src={p.image} alt="" className="h-10 w-10 rounded object-cover" /><span className="font-medium">{p.name}</span></td><td className="p-4">{p.category}</td><td className="p-4">${p.price}</td><td className={`p-4 font-semibold ${p.stock === 0 ? 'text-red-600' : p.stock <= 5 ? 'text-amber-600' : 'text-emerald-600'}`}>{p.stock === 0 ? 'Out of stock' : p.stock <= 5 ? `Low (${p.stock})` : p.stock}</td><td className="p-4">{p.rating}/5</td><td className="p-4">{p.featured ? 'Yes' : 'No'}</td><td className="flex gap-2 p-4"><Link to={`/admin/products/${p._id}/edit`} className="rounded border p-2 text-accent" aria-label="Edit product"><Pencil size={16} /></Link><button onClick={() => remove(p._id)} className="rounded border p-2 text-red-600" aria-label="Delete product"><Trash2 size={16} /></button></td></tr>) : <tr><td colSpan="7" className="p-8 text-center text-[var(--color-text-secondary)]">No products found.</td></tr>}</tbody></table></div></div>;
}
