import { useEffect, useState } from 'react';
import adminApi from '../../services/adminApi';
import toast from 'react-hot-toast';

export default function AdminReviews() {
	const [reviews, setReviews] = useState([]);
	const [search, setSearch] = useState('');
	const [rating, setRating] = useState('');
	const [sort, setSort] = useState('newest');
	const [loading, setLoading] = useState(true);
	const load = () => { setLoading(true); adminApi.getReviews({ search, rating, sort }).then(({ data }) => setReviews(data.reviews || [])).catch(() => toast.error('Failed to load reviews')).finally(() => setLoading(false)); };
	useEffect(() => { load(); }, [search, rating, sort]);
	const remove = async (id) => { if (!window.confirm('Are you sure you want to delete this review?')) return; try { await adminApi.deleteReview(id); toast.success('Review deleted'); load(); } catch { toast.error('Failed to delete review'); } };
	return <div className="space-y-6"><div><p className="text-sm text-[var(--color-text-secondary)]">Customer feedback from MongoDB</p><h2 className="text-3xl font-display">Customer Reviews</h2></div><div className="flex flex-col gap-3 md:flex-row"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search customer, product, or review" className="admin-input mt-0 md:max-w-sm" /><select value={rating} onChange={(e) => setRating(e.target.value)} className="admin-input mt-0 md:max-w-xs"><option value="">All ratings</option>{[5, 4, 3, 2, 1].map((value) => <option value={value} key={value}>{value} stars</option>)}</select><select value={sort} onChange={(e) => setSort(e.target.value)} className="admin-input mt-0 md:max-w-xs"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="highest">Highest rating</option><option value="lowest">Lowest rating</option></select></div><div className="overflow-x-auto rounded-[14px] border border-[var(--color-border)] bg-surface shadow-sm"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-ivory text-[var(--color-text-secondary)]"><tr>{['Customer', 'Product', 'Rating', 'Review', 'Date', 'Action'].map((heading) => <th className="p-4" key={heading}>{heading}</th>)}</tr></thead><tbody>{loading ? <tr><td colSpan="6" className="p-8 text-center">Loading reviews...</td></tr> : reviews.length ? reviews.map((review) => <tr className="border-t border-[var(--color-border)] align-top" key={review._id}><td className="p-4"><p className="font-medium">{review.user?.name}</p><p className="text-xs text-[var(--color-text-secondary)]">{review.user?.email}</p></td><td className="p-4">{review.product?.name || 'Deleted product'}</td><td className="p-4 text-amber-500">{'★'.repeat(review.rating)}<span className="text-[var(--color-border)]">{'★'.repeat(5 - review.rating)}</span></td><td className="max-w-sm whitespace-normal p-4 text-mocha">{review.comment}</td><td className="whitespace-nowrap p-4">{new Date(review.createdAt).toLocaleDateString()}</td><td className="p-4"><button onClick={() => remove(review._id)} className="font-medium text-red-600">Delete</button></td></tr>) : <tr><td colSpan="6" className="p-8 text-center text-[var(--color-text-secondary)]">No reviews found.</td></tr>}</tbody></table></div></div>;
}
