import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import adminApi from '../../services/adminApi';
import toast from 'react-hot-toast';

const initial = { name: '', description: '', price: '', category: 'Electronics', image: '', stock: 0, rating: 4.5, featured: false };
export default function AdminProductForm() {
  const { id } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState(initial); const [loading, setLoading] = useState(Boolean(id));
  useEffect(() => { if (id) adminApi.getProduct(id).then(({ data }) => setForm(data.product)).catch(() => toast.error('Failed to load product')).finally(() => setLoading(false)); }, [id]);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event) => { event.preventDefault(); try { const data = { ...form, price: Number(form.price), stock: Number(form.stock), rating: Number(form.rating) }; if (id) await adminApi.updateProduct(id, data); else await adminApi.createProduct(data); toast.success(id ? 'Product updated' : 'Product created'); navigate('/admin/products'); } catch (error) { toast.error(error.response?.data?.error || 'Failed to save product'); } };
  if (loading) return <p className="skeleton h-24 w-full" />;
  return <div className="max-w-3xl space-y-6"><div><p className="text-sm text-[var(--color-text-secondary)]">Catalog control</p><h2 className="text-3xl font-display">{id ? 'Edit product' : 'Add product'}</h2></div><form onSubmit={submit} className="grid gap-5 rounded-[14px] border border-[var(--color-border)] bg-surface p-6 shadow-sm sm:grid-cols-2"><label className="sm:col-span-2">Name<input required value={form.name} onChange={(e) => update('name', e.target.value)} className="admin-input" /></label><label className="sm:col-span-2">Description<textarea required value={form.description} onChange={(e) => update('description', e.target.value)} className="admin-input min-h-28" /></label><label>Price<input required min="0" step="0.01" type="number" value={form.price} onChange={(e) => update('price', e.target.value)} className="admin-input" /></label><label>Category<select value={form.category} onChange={(e) => update('category', e.target.value)} className="admin-input">{['Electronics','Clothing','Books','Home','Beauty','Sports','Other'].map((x) => <option key={x}>{x}</option>)}</select></label><label>Image URL<input value={form.image} onChange={(e) => update('image', e.target.value)} className="admin-input" /></label><label>Stock<input required min="0" type="number" value={form.stock} onChange={(e) => update('stock', e.target.value)} className="admin-input" /></label><label>Rating<input min="0" max="5" step="0.1" type="number" value={form.rating} onChange={(e) => update('rating', e.target.value)} className="admin-input" /></label><label className="flex items-center gap-2 self-end"><input type="checkbox" checked={form.featured} onChange={(e) => update('featured', e.target.checked)} /> Featured</label><div className="flex gap-3 sm:col-span-2"><button className="btn-primary" type="submit">{id ? 'Save changes' : 'Create product'}</button><button type="button" onClick={() => navigate('/admin/products')} className="rounded-lg border px-4 py-2">Cancel</button></div></form></div>;
}
